### ISSUE TITLE
quokka-themes?

### ISSUE THREAD

**Issue by QiXuanWang** [quokkaproject/quokka#203]
Lots of questions, hope you're not bored :)
How do I change themes in quokka? Through quokka_themes or flask_themes? 
I tried to modify settings.py and change "cosmo" to "foundation", nothing changed and I see "cosmo" is used in debug mode log.
Or there is only 1 working theme currently in quokka? What's the purpose of "cosmo", "default" and "foundation". 
One additional question, why do you use foundation as well as bootstrap3? Shouldn't bootstrap3 enough?

**Comment by rochacbruno** [comment]
To change a theme use the definitions of http://github.com/quokkaproject/quokka-themes no need to install anythng because quokka-themes is already installed, you just have to follow the patterns used in any of the themes https://github.com/quokkaproject/quokka/tree/master/quokka/themes.
- Cosmo is an admin theme, it is used by flask-admin
- Default is the front-end theme, used in posts, login forms, rss etc

You can create many themes you want just put the folders in /themes, in settings.py or in admin interface -> config -> settings (http://localhost:8000/admin/configview/) you can set the keys 
- DEFAULT_THEME = name of theme for front end
- ADMIN_THEME = name of the admin theme

Foundation was just removed, it was incomplete.

**Comment by QiXuanWang** [comment]
Thanks a lot. 
I noticed you have templates/ under quokka/ and themes/defaul/
files and contents are quite similar but slightly different. What's the purpose for them? 
I saw you have render_pagination() macro defined. But why can't I see it's functioning?

**Comment by rochacbruno** [comment]
Templates under quokka/templates is the one used as base in case of errors loading templates from themes.  They are not intended to be used or customized, are there just in case to have a default .

pagination are defined by a config key, default is to show 10 posts per page but you can change in settings https://github.com/quokkaproject/quokka/blob/master/quokka/core/views.py#L113

**Comment by QiXuanWang** [comment]
It helps. 
Should this templates/ thing be written in somewhere so people will get your design idea more clearly.
