### ISSUE TITLE
cannot delete posts still.

### ISSUE THREAD

**Issue by eurabilis** [quokkaproject/quokka#204]
I tried what you said I ran

pip install https://github.com/flask-admin/flask-admin/archive/v1.0.8.zip

I also reran pip install --upgrade -r requirements.txt after placing that https line in it so it didnt upgrade it again I even rebooted and made new content but I cannot delete it its not creating an id.

**Comment by rochacbruno** [comment]
```
pip uninstall flask-admin
```

to remove all the old admin files then

```
pip install https://github.com/flask-admin/flask-admin/archive/v1.0.8.zip
```

Now clear you browser cache and try again, I just tested and worked well

**Comment by eurabilis** [comment]
Sorry to say thats not working for me I cleared everything even my browsing history which i didnt want to. No luck.

**Comment by QiXuanWang** [comment]
Try to run "pip install -r requirements.txt". That's the only way that will make things work for me. 
I used "pip install https://github.com/flask-admin/flask-admin/archive/v1.0.8.zip" and it's not helping.
I guess there is some unknown dependencies on certain package.

**Comment by eurabilis** [comment]
I did that but I will try again thanks

**Comment by eurabilis** [comment]
I still cant close this bug.

**Comment by QiXuanWang** [comment]
I can reproduce it. But I don't know how I resolved this. What I remember is:
1. I use pip install Flask-Admin 1.0.8 version with recommended command. Some how it doesn't work. Then I just use pip install --upgrade Flask-Admin. Then I sync out quokka. It works after I made some manual modification to wtform package which is due to an old version of Flask-Admin.
2. Then I did some pip install things to different packages. Wrote some pages. tried to delete again. And it stopped working.
3. Then I tried some other ways, until I used "pip install -r requirements.txt", and stopped at lxml setup. But when I delete post, it worked. I then didn't do any pip things. 
What I want to say is that there is some issue in sync up.  Possibly still in Flask-Admin package

**Comment by eurabilis** [comment]
I apologize Im still learning the ins and outs of all this and it appears I was using two versions of pip both the one in the virtualenv and the global. I have fixed the problem now, upgraded and this bug is closed. Thank you all for your hard work.
