### ISSUE TITLE
Why is there no Windows installation section?

### ISSUE THREAD

**Issue by victorwestmann** [quokkaproject/quokka#218]
Can I try to create one? In the wiki of the project?
(Actually I know the answer... because serious developers don't use Windows, I guess. But this is the only thing that I have right now. Is it ok if I try to install and run this project on this environment and document all the steps?

**Comment by alexandre** [comment]
@victorwestmann ,

My 0,02 cents:

1º step -> try; you read right, just do it.
2º step -> if you think it is relevant,  just create a pull request. Even that nobody in the world uses windows, the negative answer (no), you already have.
3º step -> It's an open source project, everything is ok. (in the last case, fork it!) =]

@rochacbruno can give you a better answer.

Happy hacking and keep the enthusiasm!

[ ]'s (hugs)

**Comment by rochacbruno** [comment]
Nice, windows support and instructions are very welcome.

Documentation will be moved from WIKI to Here: https://github.com/quokkaproject/quokkaproject.github.io#how-to-contribute-to-documentation

**Comment by victorwestmann** [comment]
Ok! Just wrote how to download, install and activate virtualenv on Windows machines. :)
Now trying to make mongoDB work -- and the docs (in parallel).

**Comment by sheng01** [comment]
Hi:

I am currently running Quokka on a windows 7 machine, and having some problems -
it's definitely connecting with Mongodb - but there seems to be some issues regards
templates which I have  not been able to clearly understand.  However, where
it shows up is in the creation of a new post in the admin area - I don't
seem to have problems with reading data so far, just update or create.  

I'm sure that given some time I can work through that... However, I'm not sure when
I will get to it at this time..... Right now , for one thing - I'm being confused by github,
so, it's important for me to work through that.....

Other wise - I'm very much like the project and given the time would really like to
contribute to it in some way ---- because for one thing I think that flask and
mongodb to seem to work well together ....

Meanwhile, I'll try to pay as much attention to what is going on here as possible
at this time....
