### ISSUE TITLE
Include a filter to see only unpublished posts in admin

### ISSUE THREAD

**Issue by rochacbruno** [quokkaproject/quokka#246]

**Comment by felipevolpone** [comment]
Sorry, but it's not so clear to me, where the filter should be applied.
The filter shoud be added in which page? In the [post list](http://localhost:5000/admin/postview/) or in the [home](http://localhost:5000/admin/)?

**Comment by rochacbruno** [comment]
post list in admin, modules/post/admin.py

**Comment by rochacbruno** [comment]
Currently there is a filter
![content post quokka admin](https://cloud.githubusercontent.com/assets/458654/8696460/e59e1664-2ac2-11e5-8ab0-860342aff1e6.png)

But it is not working, there is some kind of problem loading alternatives to filter

Maybe #201 will fix this.

The code where filters is added is in core.admin and modules.post

**Comment by felipevolpone** [comment]
Now the filter is showing the options available for that item, as you can see below. This was fixed in the [this commit](https://github.com/quokkaproject/quokka/commit/d72df1fce55032676369904fb2584cb47cc82740). Btw, this issue must stay open, cause the filter of "Unpublished" wasn't developed.

![captura de tela 2015-07-19 as 00 08 14](https://cloud.githubusercontent.com/assets/1590527/8764369/567d8a74-2daa-11e5-81ad-88439ce74764.png)

**Comment by felipevolpone** [comment]
@rochacbruno Check if it's right now.

**Comment by rochacbruno** [comment]
:+1:  @felipevolpone  http://development.quokkaproject.org is ok!
