### ISSUE TITLE
Document deployment

### ISSUE THREAD

**Issue by rochacbruno** [quokkaproject/quokka#248]
uwsgi -s /tmp/uwsgi.sock -w quokka:app
gunicorn
heroku
etc

**Comment by QiXuanWang** [comment]
Is it checked in? and do you mean you will document for all of above?

**Comment by rochacbruno** [comment]
It is in progress, the deployment will be documented soon

**Comment by QiXuanWang** [comment]
I used a brand new build with "etc/scripts/setup*ubuntu.sh" to start deploy but no luck.

Here is something I tried:
I can start other Flask app succesfully but not quokka. I can run "python manager.py" or "python wsgi.py" with no problem and I can visit my site.

I'm using  uwsgi --ini method. All settings have been tuned include socket/logto/...
Then I added "wsgi-file = MY_PATH/wsgi.py" which is located under quokka/ dir. "callable = app". No errors but not working at all. Meaning I can't even visit my site. Though I can see that app is loaded and similar information is printed out, just like I did with "python manager.py".

Then I tried to add module = quokka and removed wsgi-file, it says "internal server error" and later "502 bad gateway" when visiting the web. And it stopped working when I try again just like previous. 

I'm running out of ideas now....

**Comment by rochacbruno** [comment]
Which version of ubuntu? I'll try in a VM

**Comment by QiXuanWang** [comment]
I'm using Debian8(jessie). Debian 3.16.7-ckt25-2 (2016-04-08) x86_64 GNU/Linux
The only thing I removed from setup is "emperor" related and "mount" parameter, since the syntax is somehow not working. But I think it's not impacting the function.

Update:
Some other try and now the error is:
DEBUG(cwd):  /home/quokka/quokka-env/quokka
Traceback (most recent call last):
  File "/home/quokka/quokka-env/quokka/wsgi.py", line 10, in <module>
    import quokka
ImportError: No module named quokka
unable to load app 0 (mountpoint='') (callable not found or import error)

But I do have chdir set to correct path...

**Comment by QiXuanWang** [comment]
Is there any update for this issue? I've tried different methods but now stuck at "Import Error".
I'm waiting for this to start the web. Appreciated the help!

**Comment by rochacbruno** [comment]
I am not sure if this will work on debian or only ubuntu server, I'll call some help from @jniltinho who implemented the scripts.

**Comment by QiXuanWang** [comment]
I finally make it work as root !
The mysterious thing is that even I did what others say that work for them, it still failed for me and the missing "quokka" importError is really frustrating.
