### ISSUE TITLE
Support sqlalchemy/riakalchemy

### ISSUE THREAD

**Issue by lu-zero** [quokkaproject/quokka#25]

**Comment by rochacbruno** [comment]
Hi @lu-zero this project started to be a @mongodb based CMS. In fact I choose Flask just because it plays well with Mongo and @mongoengine integrates very well.

I will not add a layer of compatibility with another dbs because some ideas will need to have too many de-normalization in relational databases.

But, If you, or somebody want to maintain this side project, I can help a bit, I can create a fork named quokka-alchemy and add you and other people to the @pythonhub organization to maintain this project.

Tks.
