### ISSUE TITLE
hmm. Is there any way to add a link to the SUMMARY of a post?

### ISSUE THREAD

**Issue by eurabilis** [quokkaproject/quokka#345]
Often times I want to add a link in the summary before I am in the actual post. I want them to see the link I add without having to click the article for example look at this. http://minecraftmafia.co/ I would like www.mebsd.com to be a link but I dont see any way of doing that. Thanks!

**Comment by rochacbruno** [comment]
@eurabilis in the current template, summary is supposed to be plain text, so there is no MARKDOWN parsing.

You can achieve this by editing the render template, edit this file: https://github.com/rochacbruno/quokka/blob/development/quokka/themes/pure/templates/_helpers.html#L119

from this

```
{{content.get_summary()|truncate(255)|safe()}}
```

in to this

```
{{markdown(content.get_summary()|safe())}}
```

Because the add of markwodn renderer the cut at 255 chars will be not allowed (can break formatting)

**Comment by eurabilis** [comment]
thank you so much I have work to do tomorrow!

**Comment by eurabilis** [comment]
Hmm I tried what you said and my site crashed. In the logs it says markdown is undefined?

**Comment by eurabilis** [comment]
clicked close by accident sorry

**Comment by rochacbruno** [comment]
humm should work as Flask-Mistune extension exposes a "markdown" function to template. I will take a look.

**Comment by eurabilis** [comment]
no rush it's not a necessity but thank you let me know.

**Comment by eurabilis** [comment]
Thank you
