### ISSUE TITLE
[Question] Blog channel type shows full post by default?

### ISSUE THREAD

**Issue by QiXuanWang** [quokkaproject/quokka#352]
Since I can't find the documentation for all channel types and those keywords/values in settings, I would like to post here.
As for "list","grid" and "portal", you have a summary view and click readmore you visit the whole post with comment system. But for "blog" type, you already get the full post. So what's the meaning of "summary" and "readmore"?  I don't know what's the difference between these channel_types. 

Please let me know which component I should check if I want to understand all those keywords/configure settings.

**Comment by rochacbruno** [comment]
@QiXuanWang good point, maybe we can clean up some elements of each template.

grid = Should show picture + title + summary with link in a grid form
portal = The same as the grid but has some highlighted contents at the top and sidebar also a carousel
blog = All the full posts opened to read and scroll continuously
list = The same as blog but shows only summary and read more instead of full post

We have to fix it

Thanks again, your contributions and ideas are very welcome

**Comment by QiXuanWang** [comment]
Man, thank you for the great work! I would contribute more later on.
I'm planning my website with quokka so I have to be serious about the quality :)
