### ISSUE TITLE
Documentation change to .rst format

### ISSUE THREAD

**Issue by ellisonleao** [quokkaproject/quokka#96]
I think we can change all docs format and user rst format , since it's the official format for python packages. What do you guys think? I can migrate this one

**Comment by rochacbruno** [comment]
I am not sure about this, the reasons.
1. We are writing the docs in the github [wiki](https://github.com/pythonhub/quokka/wiki). (because markdown is easiest than rst)
2. I don't know if the full cms should go to PyPI, the cms is an application itself, I thought about it but I cant find a way to have the CMS core in the "site-packages" and the CMS custom files in some other place (like Django does)

Maybe in near future we can release something like "quokka-admin.py" in PyPI so people can "pip install quokka" but not to have the cms, this will be only to get the "quokka-admin.py" command tool.

Currently "pip install quokka" is useless because it puts files under site-packages/quokka and no one will develop/deploy a CMS from there.

**Comment by ellisonleao** [comment]
copy that. Didn't know about the no releases policy.

**Comment by rochacbruno** [comment]
Rethinking about this, I am wondering the possibility to release the PyPI package, opened a new issue #97
